token: ""

guild_id: 123456789

mod_log: 123456789

owner_id: 164546159140929538

mod_info: 378684962934751239

timeout_id: 

dm_forward:
    - 123456789 # Me

emoji_ignore_channels:
    #Channels to ignore when counting emojis
    - 132456789

traffic_ignore_channels:
    # Channels to ignore when counting traffic
    - 123456789

spoiler_channels:
    # Channel ids to check
    - 123456789

filter_channels:
    #channel ids to filter
    - 123456798

filter_allowed:
    - ".iam Clover"
    - ".iam Member"

postgres_credentials:
    host: "localhost"
    user: "user"
    database: "nanochan"
    password: ""

# Wait time in seconds (default 10 min)
wait_time: 1800

clover_days: 3
